
export const internationalCall = [
    {
      en: 'Angola',
      es: 'Angola',
      zh_CN: '安哥拉',
      locale: 'AO',
      code: 244,
    },
    {
      en: 'Afghanistan',
      es: 'Afganistan',
      zh_CN: '阿富汗',
      locale: 'AF',
      code: 93,
    },
    {
      en: 'Albania',
      es: 'Albania',
      zh_CN: '阿尔巴尼亚',
      locale: 'AL',
      code: 355,
    },
    {
      en: 'Algeria',
      es: 'Algeria',
      zh_CN: '阿尔及利亚',
      locale: 'DZ',
      code: 213,
    },
    {
      en: 'Andorra',
      es: 'Andorra',
      zh_CN: '安道尔共和国',
      locale: 'AD',
      code: 376,
    },
    {
      en: 'Anguilla',
      es: 'Anguilla',
      zh_CN: '安圭拉岛',
      locale: 'AI',
      code: 1264,
    },
    {
      en: 'Antigua and Barbuda',
      es: 'Antigua y Barbuda',
      zh_CN: '安提瓜和巴布达',
      locale: 'AG',
      code: 1268,
    },
    {
      en: 'Argentina',
      es: 'Argentina',
      zh_CN: '阿根廷',
      locale: 'AR',
      code: 54,
    },
    {
      en: 'Armenia',
      es: 'Armenia',
      zh_CN: '亚美尼亚',
      locale: 'AM',
      code: 374,
    },
    {
      en: 'Ascension',
      es: 'Ascension',
      zh_CN: '阿森松',
      locale: 'SH',
      code: 247,
    },
    {
      en: 'Australia',
      es: 'Australia',
      zh_CN: '澳大利亚',
      locale: 'AU',
      code: 61,
    },
    {
      en: 'Austria',
      es: 'Austria',
      zh_CN: '奥地利',
      locale: 'AT',
      code: 43,
    },
    {
      en: 'Azerbaijan',
      es: 'Azerbaijan',
      zh_CN: '阿塞拜疆',
      locale: 'AZ',
      code: 994,
    },
    {
      en: 'Bahamas',
      es: 'Bahamas',
      zh_CN: '巴哈马',
      locale: 'BS',
      code: 1242,
    },
    {
      en: 'Bahrain',
      es: 'Bahrain',
      zh_CN: '巴林',
      locale: 'BH',
      code: 973,
    },
    {
      en: 'Bangladesh',
      es: 'Bangladesh',
      zh_CN: '孟加拉国',
      locale: 'BD',
      code: 880,
    },
    {
      en: 'Barbados',
      es: 'Barbados',
      zh_CN: '巴巴多斯',
      locale: 'BB',
      code: 1246,
    },
    {
      en: 'Belarus',
      es: 'Belarus',
      zh_CN: '白俄罗斯',
      locale: 'BY',
      code: 375,
    },
    {
      en: 'Belgium',
      es: 'Belgica',
      zh_CN: '比利时',
      locale: 'BE',
      code: 32,
    },
    {
      en: 'Belize',
      es: 'Belice',
      zh_CN: '伯利兹',
      locale: 'BZ',
      code: 501,
    },
    {
      en: 'Benin',
      es: 'Benin',
      zh_CN: '贝宁',
      locale: 'BJ',
      code: 229,
    },
    {
      en: 'Bermuda Is.',
      es: 'Islas Bermudas',
      zh_CN: '百慕大群岛',
      locale: 'BM',
      code: 1441,
    },
    {
      en: 'Bolivia',
      es: 'Bolivia',
      zh_CN: '玻利维亚',
      locale: 'BO',
      code: 591,
    },
    {
      en: 'Botswana',
      es: 'Botswana',
      zh_CN: '博茨瓦纳',
      locale: 'BW',
      code: 267,
    },
    {
      en: 'Brazil',
      es: 'Brasil',
      zh_CN: '巴西',
      locale: 'BR',
      code: 55,
    },
    {
      en: 'Brunei',
      es: 'Brunei',
      zh_CN: '文莱',
      locale: 'BN',
      code: 673,
    },
    {
      en: 'Bulgaria',
      es: 'Bulgaria',
      zh_CN: '保加利亚',
      locale: 'BG',
      code: 359,
    },
    {
      en: 'Burkina-faso',
      es: 'Burkina-faso',
      zh_CN: '布基纳法索',
      locale: 'BF',
      code: 226,
    },
    {
      en: 'Burma',
      es: 'Burma',
      zh_CN: '缅甸',
      locale: 'MM',
      code: 95,
    },
    {
      en: 'Burundi',
      es: 'Burundi',
      zh_CN: '布隆迪',
      locale: 'BI',
      code: 257,
    },
    {
      en: 'Cameroon',
      es: 'Camerun',
      zh_CN: '喀麦隆',
      locale: 'CM',
      code: 237,
    },
    {
      en: 'Canada',
      es: 'Canada',
      zh_CN: '加拿大',
      locale: 'CA',
      code: 1,
    },
    {
      en: 'Cayman Is.',
      es: 'Islas Cayman',
      zh_CN: '开曼群岛',
      locale: 'KY',
      code: 1345,
    },
    {
      en: 'Central African Republic',
      es: 'Republica de Africa Central',
      zh_CN: '中非共和国',
      locale: 'CF',
      code: 236,
    },
    {
      en: 'Chad',
      es: 'Chad',
      zh_CN: '乍得',
      locale: 'TD',
      code: 235,
    },
    {
      en: 'Chile',
      es: 'Chile',
      zh_CN: '智利',
      locale: 'CL',
      code: 56,
    },
    {
      en: 'China',
      es: 'China',
      zh_CN: '中国',
      locale: 'CN',
      code: 86,
    },
    {
      en: 'Colombia',
      es: 'Colombia',
      zh_CN: '哥伦比亚',
      locale: 'CO',
      code: 57,
    },
    {
      en: 'Congo',
      es: 'Congo',
      zh_CN: '刚果',
      locale: 'CG',
      code: 242,
    },
    {
      en: 'Cook Is.',
      es: 'Islas Cook',
      zh_CN: '库克群岛',
      locale: 'CK',
      code: 682,
    },
    {
      en: 'Costa Rica',
      es: 'Costa Rica',
      zh_CN: '哥斯达黎加',
      locale: 'CR',
      code: 506,
    },
    {
      en: 'Cuba',
      es: 'Cuba',
      zh_CN: '古巴',
      locale: 'CU',
      code: 53,
    },
    {
      en: 'Cyprus',
      es: 'Cyprus',
      zh_CN: '塞浦路斯',
      locale: 'CY',
      code: 357,
    },
    {
      en: 'Czech Republic',
      es: 'Republica Checa',
      zh_CN: '捷克',
      locale: 'CZ',
      code: 420,
    },
    {
      en: 'Denmark',
      es: 'Dinamarca',
      zh_CN: '丹麦',
      locale: 'DK',
      code: 45,
    },
    {
      en: 'Djibouti',
      es: 'Djibouti',
      zh_CN: '吉布提',
      locale: 'DJ',
      code: 253,
    },
    {
      en: 'Dominica Rep.',
      es: 'Republica Dominica',
      zh_CN: '多米尼加共和国',
      locale: 'DO',
      code: 1890,
    },
    {
      en: 'Ecuador',
      es: 'Ecuador',
      zh_CN: '厄瓜多尔',
      locale: 'EC',
      code: 593,
    },
    {
      en: 'Egypt',
      es: 'Egipto',
      zh_CN: '埃及',
      locale: 'EG',
      code: 20,
    },
    {
      en: 'El Salvador',
      es: 'El Salvador',
      zh_CN: '萨尔瓦多',
      locale: 'SV',
      code: 503,
    },
    {
      en: 'Estonia',
      es: 'Estonia',
      zh_CN: '爱沙尼亚',
      locale: 'EE',
      code: 372,
    },
    {
      en: 'Ethiopia',
      es: 'Etiopia',
      zh_CN: '埃塞俄比亚',
      locale: 'ET',
      code: 251,
    },
    {
      en: 'Fiji',
      es: 'Fiji',
      zh_CN: '斐济',
      locale: 'FJ',
      code: 679,
    },
    {
      en: 'Finland',
      es: 'Finlandia',
      zh_CN: '芬兰',
      locale: 'FI',
      code: 358,
    },
    {
      en: 'France',
      es: 'Francia',
      zh_CN: '法国',
      locale: 'FR',
      code: 33,
    },
    {
      en: 'French Guiana',
      es: 'Guyana Francesa',
      zh_CN: '法属圭亚那',
      locale: 'GF',
      code: 594,
    },
    {
      en: 'Gabon',
      es: 'Gabon',
      zh_CN: '加蓬',
      locale: 'GA',
      code: 241,
    },
    {
      en: 'Gambia',
      es: 'Gambia',
      zh_CN: '冈比亚',
      locale: 'GM',
      code: 220,
    },
    {
      en: 'Georgia',
      es: 'Georgia',
      zh_CN: '格鲁吉亚',
      locale: 'GE',
      code: 995,
    },
    {
      en: 'Germany',
      es: 'Alemania',
      zh_CN: '德国',
      locale: 'DE',
      code: 49,
    },
    {
      en: 'Ghana',
      es: 'Ghana',
      zh_CN: '加纳',
      locale: 'GH',
      code: 233,
    },
    {
      en: 'Gibraltar',
      es: 'Gibraltar',
      zh_CN: '直布罗陀',
      locale: 'GI',
      code: 350,
    },
    {
      en: 'Greece',
      es: 'Grecia',
      zh_CN: '希腊',
      locale: 'GR',
      code: 30,
    },
    {
      en: 'Grenada',
      es: 'Granada',
      zh_CN: '格林纳达',
      locale: 'GD',
      code: 1809,
    },
    {
      en: 'Guam',
      es: 'Guam',
      zh_CN: '关岛',
      locale: 'GU',
      code: 1671,
    },
    {
      en: 'Guatemala',
      es: 'Guatemala',
      zh_CN: '危地马拉',
      locale: 'GT',
      code: 502,
    },
    {
      en: 'Guinea',
      es: 'Guinea',
      zh_CN: '几内亚',
      locale: 'GN',
      code: 224,
    },
    {
      en: 'Guyana',
      es: 'Guyana',
      zh_CN: '圭亚那',
      locale: 'GY',
      code: 592,
    },
    {
      en: 'Haiti',
      es: 'Haiti',
      zh_CN: '海地',
      locale: 'HT',
      code: 509,
    },
    {
      en: 'Honduras',
      es: 'Honduras',
      zh_CN: '洪都拉斯',
      locale: 'HN',
      code: 504,
    },
    {
      en: 'Hongkong',
      es: 'Hongkong',
      zh_CN: '香港',
      locale: 'HK',
      code: 852,
    },
    {
      en: 'Hungary',
      es: 'Hungria',
      zh_CN: '匈牙利',
      locale: 'HU',
      code: 36,
    },
    {
      en: 'Iceland',
      es: 'Islandia',
      zh_CN: '冰岛',
      locale: 'IS',
      code: 354,
    },
    {
      en: 'India',
      es: 'India',
      zh_CN: '印度',
      locale: 'IN',
      code: 91,
    },
    {
      en: 'Indonesia',
      es: 'Indonesia',
      zh_CN: '印度尼西亚',
      locale: 'ID',
      code: 62,
    },
    {
      en: 'Iran',
      es: 'Iran',
      zh_CN: '伊朗',
      locale: 'IR',
      code: 98,
    },
    {
      en: 'Iraq',
      es: 'Iraq',
      zh_CN: '伊拉克',
      locale: 'IQ',
      code: 964,
    },
    {
      en: 'Ireland',
      es: 'Irlanda',
      zh_CN: '爱尔兰',
      locale: 'IE',
      code: 353,
    },
    {
      en: 'Israel',
      es: 'Israel',
      zh_CN: '以色列',
      locale: 'IL',
      code: 972,
    },
    {
      en: 'Italy',
      es: 'Italia',
      zh_CN: '意大利',
      locale: 'IT',
      code: 39,
    },
    {
      en: 'Ivory Coast',
      es: 'Costa de Marfil',
      zh_CN: '科特迪瓦',
      locale: 'KT',
      code: 225,
    },
    {
      en: 'Jamaica',
      es: 'Jamaica',
      zh_CN: '牙买加',
      locale: 'JM',
      code: 1876,
    },
    {
      en: 'Japan',
      es: 'Japon',
      zh_CN: '日本',
      locale: 'JP',
      code: 81,
    },
    {
      en: 'Jordan',
      es: 'Jordania',
      zh_CN: '约旦',
      locale: 'JO',
      code: 962,
    },
    {
      en: 'Kampuchea (Cambodia)',
      es: 'Camboya',
      zh_CN: '柬埔寨',
      locale: 'KH',
      code: 855,
    },
    {
      en: 'Kazakstan',
      es: 'Kazajistán',
      zh_CN: '哈萨克斯坦',
      locale: 'KZ',
      code: 327,
    },
    {
      en: 'Kenya',
      es: 'Kenia',
      zh_CN: '肯尼亚',
      locale: 'KE',
      code: 254,
    },
    {
      en: 'Korea',
      es: 'Korea',
      zh_CN: '韩国',
      locale: 'KR',
      code: 82,
    },
    {
      en: 'Kuwait',
      es: 'Kuwait',
      zh_CN: '科威特',
      locale: 'KW',
      code: 965,
    },
    {
      en: 'Kyrgyzstan',
      es: 'Kirguistán',
      zh_CN: '吉尔吉斯坦',
      locale: 'KG',
      code: 331,
    },
    {
      en: 'Laos',
      es: 'Laos',
      zh_CN: '老挝',
      locale: 'LA',
      code: 856,
    },
    {
      en: 'Latvia',
      es: 'Letonia',
      zh_CN: '拉脱维亚',
      locale: 'LV',
      code: 371,
    },
    {
      en: 'Lebanon',
      es: 'Libano',
      zh_CN: '黎巴嫩',
      locale: 'LB',
      code: 961,
    },
    {
      en: 'Lesotho',
      es: 'Lesoto',
      zh_CN: '莱索托',
      locale: 'LS',
      code: 266,
    },
    {
      en: 'Liberia',
      es: 'Liberia',
      zh_CN: '利比里亚',
      locale: 'LR',
      code: 231,
    },
    {
      en: 'Libya',
      es: 'Libia',
      zh_CN: '利比亚',
      locale: 'LY',
      code: 218,
    },
    {
      en: 'Liechtenstein',
      es: 'Liechtenstein',
      zh_CN: '列支敦士登',
      locale: 'LI',
      code: 423,
    },
    {
      en: 'Lithuania',
      es: 'Lituania',
      zh_CN: '立陶宛',
      locale: 'LT',
      code: 370,
    },
    {
      en: 'Luxembourg',
      es: 'Luxemburgo',
      zh_CN: '卢森堡',
      locale: 'LU',
      code: 352,
    },
    {
      en: 'Macao',
      es: 'Macao',
      zh_CN: '澳门',
      locale: 'MO',
      code: 853,
    },
    {
      en: 'Madagascar',
      es: 'Madagascar',
      zh_CN: '马达加斯加',
      locale: 'MG',
      code: 261,
    },
    {
      en: 'Malawi',
      es: 'Malawi',
      zh_CN: '马拉维',
      locale: 'MW',
      code: 265,
    },
    {
      en: 'Malaysia',
      es: 'Malasia',
      zh_CN: '马来西亚',
      locale: 'MY',
      code: 60,
    },
    {
      en: 'Maldives',
      es: 'Maldivas',
      zh_CN: '马尔代夫',
      locale: 'MV',
      code: 960,
    },
    {
      en: 'Mali',
      es: 'Mali',
      zh_CN: '马里',
      locale: 'ML',
      code: 223,
    },
    {
      en: 'Malta',
      es: 'Malta',
      zh_CN: '马耳他',
      locale: 'MT',
      code: 356,
    },
    {
      en: 'Mariana Is',
      es: 'Islas Marianas',
      zh_CN: '马里亚那群岛',
      locale: 'MP',
      code: 1670,
    },
    {
      en: 'Martinique',
      es: 'Martinica',
      zh_CN: '马提尼克',
      locale: 'MQ',
      code: 596,
    },
    {
      en: 'Mauritius',
      es: 'Mauricio',
      zh_CN: '毛里求斯',
      locale: 'MU',
      code: 230,
    },
    {
      en: 'Mexico',
      es: 'Mexico',
      zh_CN: '墨西哥',
      locale: 'MX',
      code: 52,
    },
    {
      en: 'Moldova, Republic of',
      es: 'Republica de Moldova',
      zh_CN: '摩尔多瓦',
      locale: 'MD',
      code: 373,
    },
    {
      en: 'Monaco',
      es: 'Monaco',
      zh_CN: '摩纳哥',
      locale: 'MC',
      code: 377,
    },
    {
      en: 'Mongolia',
      es: 'Mongolia',
      zh_CN: '蒙古',
      locale: 'MN',
      code: 976,
    },
    {
      en: 'Montserrat Is',
      es: 'Isla de Montserrat',
      zh_CN: '蒙特塞拉特岛',
      locale: 'MS',
      code: 1664,
    },
    {
      en: 'Morocco',
      es: 'Marruecos',
      zh_CN: '摩洛哥',
      locale: 'MA',
      code: 212,
    },
    {
      en: 'Mozambique',
      es: 'Mozambique',
      zh_CN: '莫桑比克',
      locale: 'MZ',
      code: 258,
    },
    {
      en: 'Namibia',
      es: 'Namibia',
      zh_CN: '纳米比亚',
      locale: 'NA',
      code: 264,
    },
    {
      en: 'Nauru',
      es: 'Nauru',
      zh_CN: '瑙鲁',
      locale: 'NR',
      code: 674,
    },
    {
      en: 'Nepal',
      es: 'Nepal',
      zh_CN: '尼泊尔',
      locale: 'NP',
      code: 977,
    },
    {
      en: 'Netheriands Antilles',
      es: 'Antillas Neerlandesas',
      zh_CN: '荷属安的列斯',
      locale: 'AN',
      code: 599,
    },
    {
      en: 'Netherlands',
      es: 'Países Bajos',
      zh_CN: '荷兰',
      locale: 'NL',
      code: 31,
    },
    {
      en: 'New Zealand',
      es: 'Nueva Zelanda',
      zh_CN: '新西兰',
      locale: 'NZ',
      code: 64,
    },
    {
      en: 'Nicaragua',
      es: 'Nicaragua',
      zh_CN: '尼加拉瓜',
      locale: 'NI',
      code: 505,
    },
    {
      en: 'Niger',
      es: 'Niger',
      zh_CN: '尼日尔',
      locale: 'NE',
      code: 227,
    },
    {
      en: 'Nigeria',
      es: 'Nigeria',
      zh_CN: '尼日利亚',
      locale: 'NG',
      code: 234,
    },
    {
      en: 'North Korea',
      es: 'Korea del Norte',
      zh_CN: '朝鲜',
      locale: 'KP',
      code: 850,
    },
    {
      en: 'Norway',
      es: 'Noruega',
      zh_CN: '挪威',
      locale: 'NO',
      code: 47,
    },
    {
      en: 'Oman',
      es: 'Oman',
      zh_CN: '阿曼',
      locale: 'OM',
      code: 968,
    },
    {
      en: 'Pakistan',
      es: 'Pakistan',
      zh_CN: '巴基斯坦',
      locale: 'PK',
      code: 92,
    },
    {
      en: 'Panama',
      es: 'Panama',
      zh_CN: '巴拿马',
      locale: 'PA',
      code: 507,
    },
    {
      en: 'Papua New Guinea',
      es: 'Papua Nueva Guinea',
      zh_CN: '巴布亚新几内亚',
      locale: 'PG',
      code: 675,
    },
    {
      en: 'Paraguay',
      es: 'Paraguay',
      zh_CN: '巴拉圭',
      locale: 'PY',
      code: 595,
    },
    {
      en: 'Peru',
      es: 'Peru',
      zh_CN: '秘鲁',
      locale: 'PE',
      code: 51,
    },
    {
      en: 'Philippines',
      es: 'Filipinas',
      zh_CN: '菲律宾',
      locale: 'PH',
      code: 63,
    },
    {
      en: 'Poland',
      es: 'Polonia',
      zh_CN: '波兰',
      locale: 'PL',
      code: 48,
    },
    {
      en: 'French Polynesia',
      es: 'Polinesia Francesa',
      zh_CN: '法属玻利尼西亚',
      locale: 'PF',
      code: 689,
    },
    {
      en: 'Portugal',
      es: 'Portugal',
      zh_CN: '葡萄牙',
      locale: 'PT',
      code: 351,
    },
    {
      en: 'Puerto Rico',
      es: 'Puerto Rico',
      zh_CN: '波多黎各',
      locale: 'PR',
      code: 1787,
    },
    {
      en: 'Qatar',
      es: 'Qatar',
      zh_CN: '卡塔尔',
      locale: 'QA',
      code: 974,
    },
    {
      en: 'Reunion',
      es: 'Reunion',
      zh_CN: '留尼旺',
      locale: 'RE',
      code: 262,
    },
    {
      en: 'Romania',
      es: 'Rumania',
      zh_CN: '罗马尼亚',
      locale: 'RO',
      code: 40,
    },
    {
      en: 'Russia',
      es: 'Rusia',
      zh_CN: '俄罗斯',
      locale: 'RU',
      code: 7,
    },
    {
      en: 'Samoa Eastern',
      es: 'Samoa Oriental',
      zh_CN: '东萨摩亚(美)',
      locale: 'AS',
      code: 684,
    },
    {
      en: 'Samoa Western',
      es: 'Samoa Occidental',
      zh_CN: '西萨摩亚',
      locale: 'WS',
      code: 685,
    },
    {
      en: 'San Marino',
      es: 'San Marino',
      zh_CN: '圣马力诺',
      locale: 'SM',
      code: 378,
    },
    {
      en: 'Sao Tome and Principe',
      es: 'Santo Tomé y Príncipe',
      zh_CN: '圣多美和普林西比',
      locale: 'ST',
      code: 239,
    },
    {
      en: 'Saudi Arabia',
      es: 'Arabia Saudita',
      zh_CN: '沙特阿拉伯',
      locale: 'SA',
      code: 966,
    },
    {
      en: 'Senegal',
      es: 'Senegal',
      zh_CN: '塞内加尔',
      locale: 'SN',
      code: 221,
    },
    {
      en: 'Seychelles',
      es: 'Seychelles',
      zh_CN: '塞舌尔',
      locale: 'SC',
      code: 248,
    },
    {
      en: 'Sierra Leone',
      es: 'Sierra Leona',
      zh_CN: '塞拉利昂',
      locale: 'SL',
      code: 232,
    },
    {
      en: 'Singapore',
      es: 'Singapur',
      zh_CN: '新加坡',
      locale: 'SG',
      code: 65,
    },
    {
      en: 'Slovakia',
      es: 'Eslovaquia',
      zh_CN: '斯洛伐克',
      locale: 'SK',
      code: 421,
    },
    {
      en: 'Slovenia',
      es: 'Eslovenia',
      zh_CN: '斯洛文尼亚',
      locale: 'SI',
      code: 386,
    },
    {
      en: 'Solomon Is',
      es: 'Islas Salomón',
      zh_CN: '所罗门群岛',
      locale: 'SB',
      code: 677,
    },
    {
      en: 'Somali',
      es: 'Somalia',
      zh_CN: '索马里',
      locale: 'SO',
      code: 252,
    },
    {
      en: 'South Africa',
      es: 'Sudafrica',
      zh_CN: '南非',
      locale: 'ZA',
      code: 27,
    },
    {
      en: 'Spain',
      es: 'España',
      zh_CN: '西班牙',
      locale: 'ES',
      code: 34,
    },
    {
      en: 'Sri Lanka',
      es: 'Sri Lanka',
      zh_CN: '斯里兰卡',
      locale: 'LK',
      code: 94,
    },
    {
      en: 'St.Lucia',
      es: 'Santa Lucia',
      zh_CN: '圣卢西亚',
      locale: 'LC',
      code: 1758,
    },
    {
      en: 'St.Vincent',
      es: 'San Vicente',
      zh_CN: '圣文森特',
      locale: 'VC',
      code: 1784,
    },
    {
      en: 'Sudan',
      es: 'Sudan',
      zh_CN: '苏丹',
      locale: 'SD',
      code: 249,
    },
    {
      en: 'Suriname',
      es: 'Suriname',
      zh_CN: '苏里南',
      locale: 'SR',
      code: 597,
    },
    {
      en: 'Swaziland',
      es: 'Suazilandia',
      zh_CN: '斯威士兰',
      locale: 'SZ',
      code: 268,
    },
    {
      en: 'Sweden',
      es: 'Suecia',
      zh_CN: '瑞典',
      locale: 'SE',
      code: 46,
    },
    {
      en: 'Switzerland',
      es: 'Suiza',
      zh_CN: '瑞士',
      locale: 'CH',
      code: 41,
    },
    {
      en: 'Syria',
      es: 'Siria',
      zh_CN: '叙利亚',
      locale: 'SY',
      code: 963,
    },
    {
      en: 'Taiwan',
      es: 'Taiwan',
      zh_CN: '台湾省',
      locale: 'TW',
      code: 886,
    },
    {
      en: 'Tajikstan',
      es: 'Tajikstan',
      zh_CN: '塔吉克斯坦',
      locale: 'TJ',
      code: 992,
    },
    {
      en: 'Tanzania',
      es: 'Tanzania',
      zh_CN: '坦桑尼亚',
      locale: 'TZ',
      code: 255,
    },
    {
      en: 'Thailand',
      es: 'Tailandia',
      zh_CN: '泰国',
      locale: 'TH',
      code: 66,
    },
    {
      en: 'Togo',
      es: 'Togo',
      zh_CN: '多哥',
      locale: 'TG',
      code: 228,
    },
    {
      en: 'Tonga',
      es: 'Tonga',
      zh_CN: '汤加',
      locale: 'TO',
      code: 676,
    },
    {
      en: 'Trinidad and Tobago',
      es: 'Trinidad y Tobago',
      zh_CN: '特立尼达和多巴哥',
      locale: 'TT',
      code: 1809,
    },
    {
      en: 'Tunisia',
      es: 'Tunisia',
      zh_CN: '突尼斯',
      locale: 'TN',
      code: 216,
    },
    {
      en: 'Turkey',
      es: 'Turquia',
      zh_CN: '土耳其',
      locale: 'TR',
      code: 90,
    },
    {
      en: 'Turkmenistan',
      es: 'Turkmenistan',
      zh_CN: '土库曼斯坦',
      locale: 'TM',
      code: 993,
    },
    {
      en: 'Uganda',
      es: 'Uganda',
      zh_CN: '乌干达',
      locale: 'UG',
      code: 256,
    },
    {
      en: 'Ukraine',
      es: 'Ucrania',
      zh_CN: '乌克兰',
      locale: 'UA',
      code: 380,
    },
    {
      en: 'United Arab Emirates',
      es: 'Emiratos Arabes Unidos',
      zh_CN: '阿拉伯联合酋长国',
      locale: 'AE',
      code: 971,
    },
    {
      en: 'United Kingdom',
      es: 'Reino unido',
      zh_CN: '英国',
      locale: 'GB',
      code: 44,
    },
    {
      en: 'United States of America',
      es: 'Estados Unidos de America',
      zh_CN: '美国',
      locale: 'US',
      code: 1,
    },
    {
      en: 'Uruguay',
      es: 'Uruguay',
      zh_CN: '乌拉圭',
      locale: 'UY',
      code: 598,
    },
    {
      en: 'Uzbekistan',
      es: 'Uzbekistan',
      zh_CN: '乌兹别克斯坦',
      locale: 'UZ',
      code: 233,
    },
    {
      en: 'Venezuela',
      es: 'Venezuela',
      zh_CN: '委内瑞拉',
      locale: 'VE',
      code: 58,
    },
    {
      en: 'Vietnam',
      es: 'Vietnam',
      zh_CN: '越南',
      locale: 'VN',
      code: 84,
    },
    {
      en: 'Yemen',
      es: 'Yemen',
      zh_CN: '也门',
      locale: 'YE',
      code: 967,
    },
    {
      en: 'Yugoslavia',
      es: 'Yugoslavia',
      zh_CN: '南斯拉夫',
      locale: 'YU',
      code: 381,
    },
    {
      en: 'Zimbabwe',
      es: 'Zimbabue',
      zh_CN: '津巴布韦',
      locale: 'ZW',
      code: 263,
    },
    {
      en: 'Zaire',
      es: 'Zaire',
      zh_CN: '扎伊尔',
      locale: 'ZR',
      code: 243,
    },
    {
      en: 'Zambia',
      es: 'Zambia',
      zh_CN: '赞比亚',
      locale: 'ZM',
      code: 260,
    },
  ];
  